platform :ios, '7.0'
pod 'FMDB'

platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '~> 3.0'
pod 'Charts'
pod 'GSMessages'
pod 'Charts'
pod 'NVActivityIndicatorView'
pod 'SwiftEventBus', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
pod 'CircleProgressView', :git => 'https://github.com/CardinalNow/iOS-CircleProgressView.git'
pod 'Timepiece'
pod 'TextFieldEffects'
pod 'SMSegmentView', '~> 1.1'
pod 'YRSideViewController', '~> 1.0'
pod 'XCGLogger', '~> 3.3'