platform :ios, '7.0'
pod 'FMDB'

platform :ios, '8.0'
use_frameworks!
pod 'Alamofire', '~> 3.0'
pod 'Charts'
pod 'PagingMenuController'
pod 'SwiftEventBus', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
pod 'CircleProgressView', :git => 'https://github.com/CardinalNow/iOS-CircleProgressView.git'
pod 'Timepiece'
pod 'SMSegmentView', '~> 1.1'
pod 'XCGLogger', '~> 3.3'
pod 'SDCycleScrollView','~> 1.3'
pod 'AutocompleteField','~> 1.1'
pod 'UIColor_Hex_Swift', '~> 2.1'
pod 'CVCalendar', '~> 1.2.9'
pod 'BRYXBanner'
pod 'RegexKitLite'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'MRProgress'
pod 'SwiftyTimer'
pod 'MSCellAccessory'
pod 'IQKeyboardManagerSwift'