//
//  Keys.swift
//  Drone
//
//  Created by leiyuncun on 16/3/15.
//  Copyright © 2016年 Cloud. All rights reserved.
//

import Foundation

let SWIFTEVENT_BUS_CONNECTION_STATE_CHANGED_KEY = "SWIFTEVENT_BUS_CONNECTION_STATE_CHANGED_KEY"

let SWIFTEVENT_BUS_FIRMWARE_VERSION_RECEIVED_KEY = "SWIFTEVENT_BUS_FIRMWARE_VERSION_RECEIVED_KEY"

let SWIFTEVENT_BUS_BIG_SYNCACTIVITY_DATA = "SWIFTEVENT_BUS_BIG_SYNCACTIVITY_DATA"

let SWIFTEVENT_BUS_BEGIN_BIG_SYNCACTIVITY = "SWIFTEVENT_BUS_BEGIN_BIG_SYNCACTIVITY"

let SWIFTEVENT_BUS_END_BIG_SYNCACTIVITY = "SWIFTEVENT_BUS_END_BIG_SYNCACTIVITY"

let SWIFTEVENT_BUS_SMALL_SYNCACTIVITY_DATA = "SWIFTEVENT_BUS_SMALL_SYNCACTIVITY_DATA"

let SWIFTEVENT_BUS_BATTERY_STATUS_CHANGED = "SWIFTEVENT_BUS_BATTERY_STATUS_CHANGED"

let SWIFTEVENT_BUS_INITIALIZATION_COMPLETED = "SWIFTEVENT_BUS_INITIALIZATION_COMPLETED"

let SELECTED_LOCATION_ADDRES = "SELECTED_LOCATION_ADDRES"

let SEARCH_ACTION_CLICK = "SEARCH_BUTTON_CLICK"

let SWIFTEVENT_OTA_PACKET_RECEIVED = "OTA_PACKET_RECEIVED"
